vim.pack.add { 'https://github.com/MeanderingProgrammer/render-markdown.nvim' }
require('render-markdown').setup {
    indent = {
        enabled = false,
        -- skip_heading = true,
    },
    heading = {
        sign = true,
        position = 'inline',
        width = 'block',
        left_margin = 0.5,
        left_pad = 0.2,
        right_pad = 0.2,
        icons = { ' ' },
        backgrounds = {
            'RenderMarkdownH1Bg',
            'RenderMarkdownH1Bg',
            'RenderMarkdownH1Bg',
            'RenderMarkdownH1Bg',
            'RenderMarkdownH1Bg',
            'RenderMarkdownH1Bg',
            -- 'RenderMarkdownH1Bg',
            -- 'RenderMarkdownH2Bg',
            -- 'RenderMarkdownH3Bg',
            -- 'RenderMarkdownH4Bg',
            -- 'RenderMarkdownH5Bg',
            -- 'RenderMarkdownH6Bg',
        },
        foregrounds = {
            'RenderMarkdownH1',
            'RenderMarkdownH2',
            'RenderMarkdownH3',
            'RenderMarkdownH4',
            'RenderMarkdownH5',
            'RenderMarkdownH6',
        },
    },
    code = {
        enabled = true,
        sign = true,
        style = 'full',
        position = 'left',
        language_pad = 0,
        language_name = true,
        disable_background = { 'diff' },
        width = 'full',
        left_margin = 0,
        left_pad = 0,
        right_pad = 0,
        min_width = 0,
        border = 'thin',
        above = '▄',
        below = '▀',
        highlight = 'RenderMarkdownCode',
        highlight_inline = 'RenderMarkdownCodeInline',
        highlight_language = nil,
    },
    link = {
        enabled = true,
        footnote = {
            superscript = true,
            prefix = '',
            suffix = '',
        },
        image = '󰥶 ',
        email = '󰀓 ',
        hyperlink = '󰌹 ',
        highlight = 'RenderMarkdownLink',
        wiki = { icon = '󱗖 ', highlight = 'RenderMarkdownWikiLink' },
        custom = {
            web = { pattern = '^http', icon = '󰖟 ' },
            youtube = { pattern = 'youtube%.com', icon = '󰗃 ' },
            github = { pattern = 'github%.com', icon = '󰊤 ' },
            neovim = { pattern = 'neovim%.io', icon = ' ' },
            stackoverflow = { pattern = 'stackoverflow%.com', icon = '󰓌 ' },
            discord = { pattern = 'discord%.com', icon = '󰙯 ' },
            reddit = { pattern = 'reddit%.com', icon = '󰑍 ' },
            sourcecpp = { pattern = '%.cpp$', icon = ' ' },
            headercpp = { pattern = '%.hpp$', icon = ' ' },
            csource = { pattern = '%.c$', icon = '󰙱 ' },
            cheader = { pattern = '%.h$', icon = ' ' },
        },
    },
    pipe_table = {
        enabled = true,
        preset = 'heavy',
        style = 'full',
        cell = 'padded',
        padding = 1,
        min_width = 0,
        border = {
            '┌',
            '┬',
            '┐',
            '├',
            '┼',
            '┤',
            '└',
            '┴',
            '┘',
            '│',
            '─',
        },
        alignment_indicator = '━',
        head = 'RenderMarkdownTableHead',
        row = 'RenderMarkdownTableRow',
        filler = 'RenderMarkdownTableFill',
    },
}
