return {
    'MeanderingProgrammer/render-markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, -- if you use the mini.nvim suite
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
    lazy = false,
    priority = 1000,
    config = function()
        require('render-markdown').setup {
            indent = {
                enabled = true,
                skip_heading = true,
            },
            code = {
                enabled = true,
                sign = true,
                style = 'full',
                position = 'left',
                language_pad = 0,
                language_name = true,
                disable_background = { 'diff' },
                width = 'full',
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = 'thin',
                above = '▄',
                below = '▀',
                highlight = 'RenderMarkdownCode',
                highlight_inline = 'RenderMarkdownCodeInline',
                highlight_language = nil,
            },
            link = {
                enabled = true,
                footnote = {
                    superscript = true,
                    prefix = '',
                    suffix = '',
                },
                image = '󰥶 ',
                email = '󰀓 ',
                hyperlink = '󰌹 ',
                highlight = 'RenderMarkdownLink',
                wiki = { icon = '󱗖 ', highlight = 'RenderMarkdownWikiLink' },
                custom = {
                    web = { pattern = '^http', icon = '󰖟 ' },
                    youtube = { pattern = 'youtube%.com', icon = '󰗃 ' },
                    github = { pattern = 'github%.com', icon = '󰊤 ' },
                    neovim = { pattern = 'neovim%.io', icon = ' ' },
                    stackoverflow = { pattern = 'stackoverflow%.com', icon = '󰓌 ' },
                    discord = { pattern = 'discord%.com', icon = '󰙯 ' },
                    reddit = { pattern = 'reddit%.com', icon = '󰑍 ' },
                    sourcecpp = { pattern = '%.cpp$', icon = ' ' },
                    headercpp = { pattern = '%.hpp$', icon = ' ' },
                    csource = { pattern = '%.c$', icon = '󰙱 ' },
                    cheader = { pattern = '%.h$', icon = ' ' },
                },
            },
            pipe_table = {
                enabled = true,
                preset = 'heavy',
                style = 'full',
                cell = 'padded',
                padding = 1,
                min_width = 0,
                border = {
                    '┌',
                    '┬',
                    '┐',
                    '├',
                    '┼',
                    '┤',
                    '└',
                    '┴',
                    '┘',
                    '│',
                    '─',
                },
                alignment_indicator = '━',
                head = 'RenderMarkdownTableHead',
                row = 'RenderMarkdownTableRow',
                filler = 'RenderMarkdownTableFill',
            },
        }
    end,
}
